---
title: "Getting started with the databoard"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r include=FALSE}

library(tidyverse)

```


```{r include=FALSE}
# Example data

# Song examples
songs <- tribble(
  ~id, ~artist,           ~title,                     ~year,
  1,   "The Beatles",     "Hey Jude",                1968,
  2,   "Michael Jackson", "Thriller",                1982,
  3,   "Queen",           "Bohemian Rhapsody",       1975,
  4,   "Adele",           "Rolling in the Deep",     2010,
  5,   "Bob Dylan",       "Like a Rolling Stone",    1965,
  6,   "Nirvana",         "Smells Like Teen Spirit", 1991,
  7,   "Madonna",         "Like a Virgin",           1984,
  8,   "Elton John",      "Your Song",               1970,
  9,   "Taylor Swift",    "Shake It Off",            2014,
  10,  "Billie Eilish",   "Bad Guy",                 2019
)

songs <- mutate(songs, text = paste0(artist,", ", title, ", ", year))

# Rule examples

rules <- tribble(
  ~category,    ~description,                                                                     ~example,
  "pop",        "Popular music with catchy melodies and broad appeal",                            "Bruno Mars - Uptown Funk",
  "rock",       "Music characterized by strong beats and electric guitars",                       "Led Zeppelin - Stairway to Heaven",
  "hip hop",    "Rhythmic music often featuring rapping and DJing",                               "Eminem - Lose Yourself",
  "jazz",       "Music with swing and blue notes, improvisation, and complex harmonies",          "John Coltrane - Giant Steps",
  "classical",  "Western art music from the medieval to the modern period",                      "Johann Sebastian Bach - Brandenburg Concerto No.3",
  "country",    "Music with roots in American folk and western styles",                           "Dolly Parton - Jolene",
  "electronic", "Music produced primarily with electronic instruments and synthesizers",          "Calvin Harris - Summer",
  "rb",         "Rhythm and Blues featuring soulful vocals and groove-based instrumentation",     "Mary J. Blige - Family Affair",
  "reggae",     "Music originating from Jamaica characterized by offbeat rhythms",                "Peter Tosh - Legalize It",
  "metal",      "Loud, aggressive rock music with distorted guitars and emphatic rhythms",        "Iron Maiden - The Trooper"
)

```


# Code
```{r include=FALSE}

# Login
da_login()

# Submit without delay
data <- llm_code(songs, text, rules)

# Once you submitted your tasks, call the same method with
# your data frame as the first parameter
# Task results that are ready will be added.
# Keep calling until all result are finished.
data <- llm_code(data)

# Inspect result
count(data, llm_result)

```


# Summarize

```{r}

# Submit without delay
data <- llm_summarize(songs, text)

# Fetch and wait max 10 seconds for each case to finish
data <- llm_summarize(data)

# Inspect the summaries
head(data$llm_result)

```

